### PR TITLE
Fix the search bar (and add bech32 search)

### LINKED ISSUE #58: Search for a txnid, get an address
Try searching (on zq2 prototestnet) for 0xe0cbc3c6545d0891d8a4b286fd5086c603b419a8a0a6d913d00c63c240cfad9b - you'll get the page for 0xfd5086C603b419a8A0A6D913D00C63C240cFAD9b which is not what you want at all..

### PR DESCRIPTION
**Pull request by rrw-zilliqa**
Closes #58

### CODE REVIEW

File: src/Header.tsx [hunk 1]
```diff
@@ -91,6 +103,109 @@ const Header: FC<HeaderProps> = ({ sourcifyPresent }) => {
...
+                          <li>
+                            {" "}
+                            Then we'll attempt an{" "}
+                            <InlineCode>BigInt</InlineCode> and try to find a
+                            block number
+                          </li>
+                          <li>
+                            {" "}
+                            Terms starting with <InlineCode>#</InlineCode> are
+                            treated as a DS block number for ZQ1
```
Comment (JamesHinshelwood) [inline src/Header.tsx:170]: FWIW I'd be in favour of deleting this if its a maintenance burden.
